server:
  port: 8001

logging:
  file:
    name: log/practical-java-elastic.log

management:
  metrics:
    export:
      elastic:
        step: 30s
        host: http://localhost:9200


springdoc:
  swagger-ui:
    supported-submit-methods:
      - get
